language: julia
os:
  - linux
julia:
  - 1.0
notifications:
  email: true
jobs:
  include:
    - stage: "Documentation"
      julia: 1.0
      os: linux
      script:
        - julia --project=book/ -e 'using Pkg; Pkg.develop(PackageSpec(path=pwd()));
                                               Pkg.instantiate()'
        - julia --project=book/ docs/make.jl
      after_success: skip